# Generated by Django 5.2.4 on 2025-07-12 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Поисковый запрос",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название товара"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена со скидкой",
                    ),
                ),
                ("rating", models.FloatField(verbose_name="Рейтинг")),
                (
                    "count_review",
                    models.PositiveIntegerField(
                        verbose_name="Количество отзывов"
                    ),
                ),
                (
                    "parse_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата парсинга",
                    ),
                ),
                (
                    "product_id",
                    models.BigIntegerField(
                        default=0, unique=True, verbose_name="ID товара на WB"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["search_query"],
                        name="parser_prod_search__3a36ff_idx",
                    ),
                    models.Index(
                        fields=["parse_at"],
                        name="parser_prod_parse_a_5f7831_idx",
                    ),
                    models.Index(
                        fields=["product_id"],
                        name="parser_prod_product_724159_idx",
                    ),
                ],
            },
        ),
    ]
