# Generated by Django 5.2.4 on 2025-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="parse_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата парсинга"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="ID товара на WB"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="search_query",
            field=models.CharField(
                max_length=255, verbose_name="Поисковый запрос"
            ),
        ),
    ]
