# Generated by Django 5.2.4 on 2025-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser",
            "0002_alter_product_parse_at_alter_product_product_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-parse_at"]},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="parser_prod_parse_a_5f7831_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="parser_prod_product_724159_idx",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["price"], name="parser_prod_price_b711dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["rating"], name="parser_prod_rating_04f9ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["count_review"], name="parser_prod_count_r_97995a_idx"
            ),
        ),
    ]
